language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    # Spark 2.0.0
    - jdk: openjdk7
      scala: 2.11.8
      env: TEST_SPARK_VERSION="2.0.0" LUCENE_ANALYZER="en"
    - jdk: oraclejdk8
      scala: 2.11.8
      env: TEST_SPARK_VERSION="2.0.0" LUCENE_ANALYZER="en"
    - jdk: oraclejdk8
      scala: 2.11.8
      env: TEST_SPARK_VERSION="2.0.0" LUCENE_ANALYZER="whitespace"
script:
#  - sbt ++$TRAVIS_SCALA_VERSION clean update coverage -Dlucenerdd.analyzer.name=${LUCENE_ANALYZER} -test
  - sbt ++$TRAVIS_SCALA_VERSION clean update coverage -Dlucenerdd.analyzer.name=${LUCENE_ANALYZER}
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION assembly
after_success: "sbt coverageReport coveralls"

